<a id="top"></a>
# Reading Data from Various Sources — Complete Notes

A structured, linkable reference covering how to load data into pandas from different sources: JSON files, a CSV hosted at a URL, HTML tables scraped from a webpage, and Excel files.

---

## 📑 Table of Contents

- [Setup](#setup)
- [Reading & Writing JSON](#reading-json)
- [Reading CSV from a URL](#reading-csv-url)
- [Reading Tables from HTML (Web Scraping)](#reading-html)
- [Reading Excel Files](#reading-excel)

---

<a id="setup"></a>
## Setup

Importing pandas and numpy, used throughout this notebook.

In [13]:
import pandas as pd
import numpy as np

<a id="reading-json"></a>
## Reading & Writing JSON

Loading data from a JSON file with `read_json()`, and converting a DataFrame back into JSON using different layouts — `orient='index'` and `orient='records'` — with `to_json()`.

In [14]:
df=pd.read_json("students.json")
print(df)

  student_id    name  university  stipend
0     STU101   Noman  UET Taxila  25000.0
1     STU102  Salman  UET Taxila  20000.0
2     STU103   Ahmed        NUST      NaN

In [15]:
# again to json convert
df.to_json()

'{"student_id":{"0":"STU101","1":"STU102","2":"STU103"},"name":{"0":"Noman","1":"Salman","2":"Ahmed"},"university":{"0":"UET Taxila","1":"UET Taxila","2":"NUST"},"stipend":{"0":25000.0,"1":20000.0,"2":null}}'

In [ ]:
# using the index orient
df.to_json(orient='index')
# that is giving the values index wise

'{"0":{"student_id":"STU101","name":"Noman","university":"UET Taxila","stipend":25000.0},"1":{"student_id":"STU102","name":"Salman","university":"UET Taxila","stipend":20000.0},"2":{"student_id":"STU103","name":"Ahmed","university":"NUST","stipend":null}}'

In [19]:
# shows the original one given data 
df.to_json(orient='records')

'[{"student_id":"STU101","name":"Noman","university":"UET Taxila","stipend":25000.0},{"student_id":"STU102","name":"Salman","university":"UET Taxila","stipend":20000.0},{"student_id":"STU103","name":"Ahmed","university":"NUST","stipend":null}]'

<a id="reading-csv-url"></a>
## Reading CSV from a URL

Reading a CSV file directly from a URL — no need to download it first — then saving the result back to a local file with `to_csv()`.

In [20]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

In [21]:
df.head(5)

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [22]:
df.size

2478

In [23]:
df.to_csv('wine.csv')

<a id="reading-html"></a>
## Reading Tables from HTML (Web Scraping)

Pulling every table straight out of a webpage with `read_html()` — it returns a list of all tables found on the page, so you pick out the one you actually want.

In [46]:
url='https://www.fdic.gov/bank-failures/failed-bank-list/'

In [47]:
df=pd.read_html(url)

In [49]:
df=df[0]
df

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

In [51]:
df.set_index('Bank Name', inplace=True)

In [52]:
df

,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
Bank Name,,,,,,
Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
"Guaranty Bank, (d/b/a BestBank in Georgia & Michigan)",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

<a id="reading-excel"></a>
## Reading Excel Files

Installing `openpyxl` (needed to read `.xlsx` files) and loading an Excel file into a DataFrame with `read_excel()`.

In [61]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [65]:
excel_df=pd.read_excel('Sample_data.xlsx')
excel_df.set_index('LoanID').head(10)

       BookID MemberID   BorrowDate   ReturnDate    Status  Fine_PKR
LoanID
L00126  B0068  MEM0048  25-Jan-2025          NaN   Overdue     355.0
L00058  B0043  MEM0058   2024-10-20          NaN   Overdue     230.0
L00284  B0011  MEM0067  26-Jan-2024          NaN   Ongoing       0.0
L00067  B0001  MEM0071   2024-08-20          NaN   Ongoing       0.0
L00115  B0088  MEM0031  17-May-2024  08-Jun-2024  Returned       0.0
L00283  B0075  MEM0052  06-Dec-2024          NaN   Overdue     286.0
L00133  B0056  MEM0026  23-May-2024  17-Jun-2024  Returned       0.0
L00259  B0055  MEM0070   2025-04-09          NaN   Ongoing       0.0
L00038  B0067  MEM0075  06-Apr-2025          NaN   Ongoing       0.0
L00275  B0078  MEM0041  15-Dec-2024          NaN   Ongoing       0.0

---

[🔼 Back to Table of Contents](#top)

🎉 **End of Notes**