In [1]:
import numpy as numpy
import pandas as pd

In [2]:
movies=pd.read_csv("movies.csv")
movies

,MovieID,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
0,M0072,The Eternal Signal,Sci-Fi,2009,Anna Johnson,Urdu,180,5.7,15685,26.1
1,M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0
2,M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8
3,M0103,The Shattered Empire,Animation,2014,Mina Ahmed,Hindi,101,5.8,2579,8.3
4,M0003,The Frozen Path,Action,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0
...,...,...,...,...,...,...,...,...,...,...
148,M0048,The Silent Echo,Comedy,2018,James Chen,Punjabi,96,3.4,32466,8.8
149,M0080,The Broken Flame,Action,2007,Ayesha Smith,Hindi,128,7.1,2559,12.1
150,M0110,The Eternal River,Sci-Fi,2014,Hassan Ahmed,Punjabi,116,7.4,68089,33.7
151,M0107,The Eternal Shadow,Romance,2019,Nadia Garcia,Hindi,133,8.9,11474,1.2
152,M0139,The Frozen Warrior,Documentary,2019,Omar Ahmed,Punjabi,127,7.6,27238,NaN

In [3]:
movies.shape

(153, 10)

In [4]:
movies.columns

Index(['MovieID', 'Title', 'Genre', 'ReleaseYear', 'Director', 'Language',
       'Duration_min', 'IMDB_Rating', 'Votes', 'BoxOffice_Million_USD'],
      dtype='str')

In [5]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MovieID                153 non-null    str
 1   Title                  153 non-null    str
 2   Genre                  153 non-null    str
 3   ReleaseYear            153 non-null    int64
 4   Director               153 non-null    str
 5   Language               153 non-null    str
 6   Duration_min           153 non-null    int64
 7   IMDB_Rating            144 non-null    float64
 8   Votes                  153 non-null    int64
 9   BoxOffice_Million_USD  143 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 12.1 KB

In [18]:
genres=movies.groupby('Genre')
genres.min().head(3)

,MovieID,Title,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
Genre,,,,,,,,,
Action,M0003,The Broken Flame,1998,Ahmed Chen,English,75,5.4,2559,4.7
Animation,M0019,The Dark Dream,1999,Anna Garcia,English,75,4.8,1708,1.2
Comedy,M0001,The Burning Dream,1999,Ahmed Garcia,ENGLISH,75,3.4,3696,1.7

In [ ]:
genres.max().head(3)
# can apply any aggregates function on the group by output data

,MovieID,Title,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
Genre,,,,,,,,,
Action,M0134,The Lost Garden,2026,Wei Lee,Urdu,128,9.2,102833,70.1
Animation,M0147,The Silent Path,2024,Wei Rodriguez,spanish,152,8.2,220191,116.6
Comedy,M0144,The Silent Echo,2025,Robert Farooq,spanish,153,9.1,172965,56.4

In [ ]:
# let try to fetch out the voting viva genre
movies['Genre']=movies['Genre'].str.title().str.strip()
# the above code is writen for the title case overcome
movies.groupby('Genre').sum()['Votes'].sort_values(ascending=False)
# After group by took sum and just showed the  votes columns

Genre
Comedy         989230
Sci-Fi         891948
Animation      848444
Drama          749591
Thriller       728470
Documentary    688870
Horror         642524
Romance        550047
Action         523956
Name: Votes, dtype: int64

In [21]:
# if i want to fetch out the top 3 voted movies then
movies.groupby('Genre').sum()['Votes'].sort_values(ascending=False).head(3)

Genre
Comedy       989230
Sci-Fi       891948
Animation    848444
Name: Votes, dtype: int64

In [22]:
# the best method is that first fetch the columns 
# then apply the desired formula on that
movies.groupby('Genre')['Votes'].sum().sort_values(ascending=False).head(3)

Genre
Comedy       989230
Sci-Fi       891948
Animation    848444
Name: Votes, dtype: int64

In [31]:
# mean on the basis of the rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Drama          7.161111
Romance        7.131250
Action         6.861538
Documentary    6.823529
Horror         6.770000
Animation      6.460000
Comedy         6.450000
Sci-Fi         6.375000
Thriller       6.276471
Name: IMDB_Rating, dtype: float64

In [28]:
# find the highest avg imdg_rating on the  basis of the genre

movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(3)

Genre
Drama      7.161111
Romance    7.131250
Action     6.861538
Name: IMDB_Rating, dtype: float64

In [ ]:
# find the highest max 3 imdg_rating on the  basis of the genre

movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(3)

Genre
Drama          9.6
Documentary    9.5
Action         9.2
Name: IMDB_Rating, dtype: float64

In [41]:
movies['Director']=movies['Director'].str.title().str.strip()
movies.groupby('Director')['Votes'].sum().sort_values(ascending=False).head(5)

Director
Michael Khan    245691
Carlos Khan     229578
Wei Garcia      226862
Carlos Chen     220203
Carlos Ahmed    220191
Name: Votes, dtype: int64

In [42]:
# and if want to find out the top 1
movies.groupby('Director')['Votes'].sum().sort_values(ascending=False).head(1)

Director
Michael Khan    245691
Name: Votes, dtype: int64

In [44]:
movies.columns

Index(['MovieID', 'Title', 'Genre', 'ReleaseYear', 'Director', 'Language',
       'Duration_min', 'IMDB_Rating', 'Votes', 'BoxOffice_Million_USD'],
      dtype='str')

In [45]:
# find the highest rated movies of each genre
movies.groupby('Genre')['IMDB_Rating'].sum().sort_values(ascending=False)

Genre
Drama          128.9
Sci-Fi         127.5
Comedy         116.1
Documentary    116.0
Romance        114.1
Thriller       106.7
Animation       96.9
Action          89.2
Horror          67.7
Name: IMDB_Rating, dtype: float64

In [57]:
movies.groupby('Genre')['ReleaseYear'].value_counts().sort_values(ascending=False).head(10)

Genre        ReleaseYear
Thriller     2019           5
             2014           4
Drama        2017           3
Documentary  2004           3
Sci-Fi       2014           3
             2024           3
Comedy       2018           3
Action       2007           2
Animation    2015           2
Comedy       2019           2
Name: count, dtype: int64

In [59]:
movies.groupby('Genre')['ReleaseYear'].count().sort_values(ascending=False).head(10)

Genre
Sci-Fi         21
Drama          19
Comedy         19
Thriller       18
Documentary    18
Romance        17
Animation      16
Action         15
Horror         10
Name: ReleaseYear, dtype: int64

In [60]:
# i want to check that how many groups are made
len(movies.groupby('Genre'))

9

In [ ]:
# same output can be done viva this
movies['Genre'].nunique()

9

In [ ]:
# that shows that how many rows are in each groups
# sorted on the basis of the index
movies.groupby('Genre').size()

Genre
Action         15
Animation      16
Comedy         19
Documentary    18
Drama          19
Horror         10
Romance        17
Sci-Fi         21
Thriller       18
dtype: int64

In [ ]:
movies['Genre'].value_counts()
# sorted on the basis of values

Genre
Sci-Fi         21
Comedy         19
Drama          19
Thriller       18
Documentary    18
Romance        17
Animation      16
Action         15
Horror         10
Name: count, dtype: int64

In [70]:
movies['Genre']=movies['Genre'].str.title().str.strip()
genre=movies.groupby('Genre')
genre.first()

,MovieID,Title,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
Genre,,,,,,,,,
Action,M0003,The Frozen Path,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0
Animation,M0103,The Shattered Empire,2014,Mina Ahmed,Hindi,101,5.8,2579,8.3
Comedy,M0108,The Rising Shadow,2019,Mina Khan,English,98,6.9,94388,24.0
Documentary,M0065,The Hidden Dream,2014,Omar Khan,URDU,130,7.6,92583,43.0
Drama,M0031,The Forgotten Echo,2017,David Rodriguez,Urdu,110,5.8,11686,26.1
Horror,M0105,The Rising City,2008,Sofia Ahmed,Urdu,89,6.2,96447,16.4
Romance,M0138,The Last Signal,2006,Hassan Smith,English,112,8.2,7053,1.3
Sci-Fi,M0072,The Eternal Signal,2009,Anna Johnson,Urdu,180,5.7,15685,26.1
Thriller,M0089,The Frozen Dream,2014,James Johnson,Spanish,116,5.3,10318,5.5

In [ ]:
# this will give the last one columns of every groups
genre.last()

,MovieID,Title,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
Genre,,,,,,,,,
Action,M0080,The Broken Flame,2007,Ayesha Smith,Hindi,128,7.1,2559,12.1
Animation,M0131,The Dark Shadow,2018,Anna Garcia,English,125,8.1,107130,36.7
Comedy,M0048,The Silent Echo,2018,James Chen,Punjabi,96,3.4,32466,8.8
Documentary,M0139,The Frozen Warrior,2019,Omar Ahmed,Punjabi,127,7.6,27238,26.5
Drama,M0063,The Rising Dream,2019,Carlos Khan,Spanish,141,7.3,11249,48.9
Horror,M0087,The Frozen Promise,2020,Carlos Rodriguez,Spanish,92,6.2,17343,73.8
Romance,M0107,The Eternal Shadow,2019,Nadia Garcia,Hindi,133,8.9,11474,1.2
Sci-Fi,M0110,The Eternal River,2014,Hassan Ahmed,Punjabi,116,7.4,68089,33.7
Thriller,M0009,The Final Signal,2019,Mina Chen,Urdu,119,7.3,3723,12.2