In [2]:
import numpy as np
import pandas as pd

In [3]:
nov_data=pd.read_csv('nov.csv')
dec_data=pd.read_csv('dec.csv')
courses=pd.read_csv('courses.csv')
students=pd.read_csv('students.csv')

In [4]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [5]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20

In [6]:
nov_data

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9
5          18          1
6           1          1
7           7          8
8          22          3

In [7]:
dec_data

   student_id  course_id
0           3          5
1          16          7
2          12         10
3          12          1
4          14          9
5           7          7
6           7          2
7          16          3
8          17         10

## Vertical Combining

In [8]:
# concatination of different files in ones
registration=pd.concat([nov_data,dec_data],ignore_index=True)
registration

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9            3          5
10          16          7
11          12         10
12          12          1
13          14          9
14           7          7
15           7          2
16          16          3
17          17         10

In [9]:
# this is the multi index as november & dec and also by default index in mantained
multi_index=pd.concat([nov_data,dec_data],keys=['November','December'])
multi_index

            student_id  course_id
November 0          23          1
         1          15          5
         2          18          6
         3          23          4
         4          16          9
         5          18          1
         6           1          1
         7           7          8
         8          22          3
December 0           3          5
         1          16          7
         2          12         10
         3          12          1
         4          14          9
         5           7          7
         6           7          2
         7          16          3
         8          17         10

In [10]:
# try to fetch on the basis of the index
multi_index.loc['November']

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9
5          18          1
6           1          1
7           7          8
8          22          3

In [ ]:
# let say if i want to get the desired index data of the november or the december
# november 5th record
multi_index.loc[('November',4)]

student_id    16
course_id      9
Name: (November, 4), dtype: int64

In [ ]:
# december 9th record
multi_index.loc[('December',8)]

student_id    17
course_id     10
Name: (December, 8), dtype: int64

## Horizontal Combining
# or side by side combining

In [ ]:
# here axis 1 shows the columns 
horizontl_combining=pd.concat([nov_data,dec_data],axis=1)
horizontl_combining

   student_id  course_id  student_id  course_id
0          23          1           3          5
1          15          5          16          7
2          18          6          12         10
3          23          4          12          1
4          16          9          14          9
5          18          1           7          7
6           1          1           7          2
7           7          8          16          3
8          22          3          17         10

In [14]:
horizontl_combining.shape

(9, 4)