In [1]:
import numpy as np
import pandas as pd

In [2]:

# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multi_index=pd.MultiIndex.from_tuples(index_val)
multi_index
# 2. pd.MultiIndex.from_product()

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [3]:
# 2. can also make by the cartesian product
multi_index_2=pd.MultiIndex.from_product([['cse','ece'],[2021,2022,2023,2024]])
multi_index_2

MultiIndex([('cse', 2021),
            ('cse', 2022),
            ('cse', 2023),
            ('cse', 2024),
            ('ece', 2021),
            ('ece', 2022),
            ('ece', 2023),
            ('ece', 2024)],
           )

In [4]:
# gives the levels
multi_index.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [8]:
multi_index_2.levels

FrozenList([['cse', 'ece'], [2021, 2022, 2023, 2024]])

In [4]:
# fetching th levels
multi_index.levels[0]

Index(['cse', 'ece'], dtype='str')

In [9]:
multi_index_2.levels[0]

Index(['cse', 'ece'], dtype='str')

In [5]:
multi_index.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [10]:
multi_index_2.levels[1]

Index([2021, 2022, 2023, 2024], dtype='int64')

In [7]:
# creating a series from the  multi_index objects
s=pd.Series([1,2,3,4,5,6,7,8],index=multi_index)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [8]:
# now fetching the elements
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [10]:
print(s[('cse',2021)])

3

In [13]:
# we can also make its 2d dfa viva unstack()
temp=s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [14]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [ ]:
branch_student=pd.DataFrame(
       [
           [1,2],
            [3,4],
             [5,6],
              [7,8],
               [9,10],
                [11,12],
                 [13,14],
                 [15,16]
       ],
       index=multi_index,
       columns=['avg_package','students']
)
branch_student

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [16]:
branch_student.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [17]:
branch_student.loc['ece']

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [18]:

# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['Multan','islamabad'],['avg_package','students']])
)

branch_df2

          Multan            islamabad
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [19]:
branch_df2['Multan']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [20]:
branch_df2['islamabad']

      avg_package  students
2019            0         0
2020            0         0
2021            0         0
2022            0         0

In [21]:
branch_df2['Multan']['students']

2019    2
2020    4
2021    6
2022    8
Name: students, dtype: int64

In [23]:
branch_df2.loc[2019]

Multan     avg_package    1
           students       2
islamabad  avg_package    0
           students       0
Name: 2019, dtype: int64

In [26]:

# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multi_index,
    columns = pd.MultiIndex.from_product([['Multan','Islamabad'],['avg_package','students']])
)

branch_df3

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## Stacking and unstacking

In [27]:
branch_student

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [28]:
branch_student.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [29]:
branch_student.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [34]:
branch_student.unstack().stack().stack()

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [35]:
branch_df2

          Multan            islamabad
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [ ]:
branch_df2.unstack()# converts the rows into columns

Multan     avg_package  2019    1
                        2020    3
                        2021    5
                        2022    7
           students     2019    2
                        2020    4
                        2021    6
                        2022    8
islamabad  avg_package  2019    0
                        2020    0
                        2021    0
                        2022    0
           students     2019    0
                        2020    0
                        2021    0
                        2022    0
dtype: int64

In [ ]:
branch_df2.stack()
# converts the inner rows into columns

                  Multan  islamabad
2019 avg_package       1          0
     students          2          0
2020 avg_package       3          0
     students          4          0
2021 avg_package       5          0
     students          6          0
2022 avg_package       7          0
     students          8          0

In [39]:
branch_df3

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [40]:
branch_df3.unstack()

         Multan                                          Islamabad            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [41]:
# by applying again unstack it will convert into series
branch_df3.unstack().unstack()

Multan     avg_package  2019  cse     1
                              ece     9
                        2020  cse     3
                              ece    11
                        2021  cse     5
                              ece    13
                        2022  cse     7
                              ece    15
           students     2019  cse     2
                              ece    10
                        2020  cse     4
                              ece    12
                        2021  cse     6
                              ece    14
                        2022  cse     8
                              ece    16
Islamabad  avg_package  2019  cse     0
                              ece     0
                        2020  cse     0
                              ece     0
                        2021  cse     0
                              ece     0
                        2022  cse     0
                              ece     0
           students     2019  cse     0
                              ece     0
                        2020  cse     0
                              ece     0
                        2021  cse     0
                              ece     0
                        2022  cse     0
                              ece     0
dtype: int64

In [43]:
branch_df3.stack().stack()

cse  2019  avg_package  Multan        1
                        Islamabad     0
           students     Multan        2
                        Islamabad     0
     2020  avg_package  Multan        3
                        Islamabad     0
           students     Multan        4
                        Islamabad     0
     2021  avg_package  Multan        5
                        Islamabad     0
           students     Multan        6
                        Islamabad     0
     2022  avg_package  Multan        7
                        Islamabad     0
           students     Multan        8
                        Islamabad     0
ece  2019  avg_package  Multan        9
                        Islamabad     0
           students     Multan       10
                        Islamabad     0
     2020  avg_package  Multan       11
                        Islamabad     0
           students     Multan       12
                        Islamabad     0
     2021  avg_package  Multan       13
                        Islamabad     0
           students     Multan       14
                        Islamabad     0
     2022  avg_package  Multan       15
                        Islamabad     0
           students     Multan       16
                        Islamabad     0
dtype: int64

## Working with the Multi_index

In [44]:
branch_df3.head()

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0

In [45]:
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Multan, avg_package)     8 non-null      int64
 1   (Multan, students)        8 non-null      int64
 2   (Islamabad, avg_package)  8 non-null      int64
 3   (Islamabad, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 820.0+ bytes

In [46]:
branch_df3.duplicated()

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [47]:
branch_df3.isnull()

              Multan            Islamabad
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [48]:
# extracting single row
branch_df3.loc['cse',2022]

Multan     avg_package    7
           students       8
Islamabad  avg_package    0
           students       0
Name: (cse, 2022), dtype: int64

In [50]:
# multiple
branch_df3.loc[('cse',2019):('ece',2020):2]

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [55]:
branch_df3.iloc[1]

Multan     avg_package    3
           students       4
Islamabad  avg_package    0
           students       0
Name: (cse, 2020), dtype: int64

In [56]:
branch_df3.iloc[0:5:2]

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

## Extracting Columns

In [57]:
branch_df3['Multan']

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [58]:
branch_df3['Multan']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [60]:
branch_df3.iloc[:,1:3]

           Multan   Islamabad
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [61]:
# extracting the both
# viva fancy indexing
branch_df3.iloc[[1,2],[2,3]]

           Islamabad
         avg_package students
cse 2020           0        0
    2021           0        0

In [62]:
branch_df3.iloc[[1,2],:]

              Multan            Islamabad
         avg_package students avg_package students
cse 2020           3        4           0        0
    2021           5        6           0        0

In [63]:
branch_df3.iloc[:,[2,3]]

           Islamabad
         avg_package students
cse 2019           0        0
    2020           0        0
    2021           0        0
    2022           0        0
ece 2019           0        0
    2020           0        0
    2021           0        0
    2022           0        0

## sorting

In [64]:
branch_df3.sort_index(ascending=False)

              Multan            Islamabad
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [65]:
branch_df3.sort_index(ascending=[False,True])

              Multan            Islamabad
         avg_package students avg_package students
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0

In [70]:
branch_df3.sort_index(level=0,ascending=False)

              Multan            Islamabad
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [71]:
branch_df3.sort_index(level=1,ascending=False)

              Multan            Islamabad
         avg_package students avg_package students
ece 2022          15       16           0        0
cse 2022           7        8           0        0
ece 2021          13       14           0        0
cse 2021           5        6           0        0
ece 2020          11       12           0        0
cse 2020           3        4           0        0
ece 2019           9       10           0        0
cse 2019           1        2           0        0

In [72]:
branch_df3

              Multan            Islamabad
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [74]:
branch_df3.transpose()

                       cse                 ece
                      2019 2020 2021 2022 2019 2020 2021 2022
Multan    avg_package    1    3    5    7    9   11   13   15
          students       2    4    6    8   10   12   14   16
Islamabad avg_package    0    0    0    0    0    0    0    0
          students       0    0    0    0    0    0    0    0

## Swap level