In [13]:
import numpy as np
import pandas as pd

## Creating Pandas

In [3]:
# from  2d   list
student_rec=[
    [100,96,10],
    [90,80,8],
    [76,56,7],
    [66,60,5]
]
df1=pd.DataFrame(student_rec,columns=['iq','Marks','Package'])

In [87]:
# from dictionary
import pandas as pd

# Data in the form of a dictionary
data_dict = {
    "Subject": [
        "Mathematics",
        "Computer Science",
        "Physics",
        "Chemistry",
        "English",
        "Data Science",
        "Machine Learning",
        "Operating Systems",
        "Digital Logic Design",
        "Technical Writing",
    ],
    "Marks_Obtained": [85, 92, 78, 83, 88, 95, 90, 81, 87, 84],
    "Total_Marks": [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
    "Grade": ["A", "A+", "B", "B+", "A", "A+", "A+", "B+", "A", "B+"],
}

# Create the DataFrame
student_record = pd.DataFrame(data_dict)
student_record.set_index("Subject",inplace=True)
# View the DataFrame
print(student_record)

                      Marks_Obtained  Total_Marks Grade
Subject
Mathematics                       85          100     A
Computer Science                  92          100    A+
Physics                           78          100     B
Chemistry                         83          100    B+
English                           88          100     A
Data Science                      95          100    A+
Machine Learning                  90          100    A+
Operating Systems                 81          100    B+
Digital Logic Design              87          100     A
Technical Writing                 84          100    B+

## Read CSV

In [73]:
movies=pd.read_csv('movies.csv')
movies.set_index("MovieID",inplace=True)
movies

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0072,The Eternal Signal,Sci-Fi,2009,Anna Johnson,Urdu,180,5.7,15685,26.1
M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0
M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8
M0103,The Shattered Empire,Animation,2014,Mina Ahmed,Hindi,101,5.8,2579,8.3
M0003,The Frozen Path,Action,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0
...,...,...,...,...,...,...,...,...,...
M0048,The Silent Echo,Comedy,2018,James Chen,Punjabi,96,3.4,32466,8.8
M0080,The Broken Flame,Action,2007,Ayesha Smith,Hindi,128,7.1,2559,12.1
M0110,The Eternal River,Sci-Fi,2014,Hassan Ahmed,Punjabi,116,7.4,68089,33.7
M0107,The Eternal Shadow,Romance,2019,Nadia Garcia,Hindi,133,8.9,11474,1.2
M0139,The Frozen Warrior,Documentary,2019,Omar Ahmed,Punjabi,127,7.6,27238,NaN

In [74]:
psl_matches=pd.read_csv('psl_matches.csv')
psl_matches.set_index('MatchID',inplace=True)
psl_matches

,Season,Date,Team1,Team2,Venue,TossWinner,TossDecision,Team1_Score,Team2_Score,Winner,PlayerOfTheMatch
MatchID,,,,,,,,,,,
PSL0026,2021,07/03/2021,Karachi Kings,Lahore Qalandars,Rawalpindi Cricket Stadium,Lahore Qalandars,Field,120/2,130/10,Karachi Kings,Player 39
PSL0053,2022,2022-02-28,Peshawar Zalmi,multan sultans,"Gaddafi Stadium, Lahore",Multan Sultans,Field,150/4,138/6,Peshawar Zalmi,Player 8
PSL0150,2025,23-Feb-2025,Lahore Qalandars,Multan Sultans,Pindi Cricket Stadium,Lahore Qalandars,Bat,161/6,135/5,Multan Sultans,Player 29
PSL0089,2023,02/03/2023,Karachi Kings,Quetta Gladiators,Rawalpindi Cricket Stadium,Karachi Kings,Bat,141/4,183/7,Quetta Gladiators,Player 40
PSL0114,2024,2024-02-21,Karachi Kings,Islamabad United,"National Stadium, Karachi",Karachi Kings,Bat,125/5,151/2,Karachi Kings,Player 5
...,...,...,...,...,...,...,...,...,...,...,...
PSL0084,2023,2023-02-25,Multan Sultans,Peshawar Zalmi,Pindi Cricket Stadium,Peshawar Zalmi,Bat,129/4,213/4,NaN,NaN
PSL0137,2025,2025-02-10,LAHORE QALANDARS,Peshawar Zalmi,"Gaddafi Stadium, Lahore",Peshawar Zalmi,Field,132/5,141/2,NaN,NaN
PSL0134,2024,12-Mar-2024,Lahore Qalandars,Karachi Kings,"Gaddafi Stadium, Lahore",Karachi Kings,Bat,215/7,195/6,Karachi Kings,Player 9
PSL0106,2024,13-Feb-2024,Islamabad United,Multan Sultans,"National Stadium, Karachi",Islamabad United,Field,129/3,169/3,Islamabad United,Player 3
PSL0085,2023,2023-02-26,Lahore Qalandars,Peshawar Zalmi,Rawalpindi Cricket Stadium,Lahore Qalandars,Bat,167/6,160/3,Lahore Qalandars,Player 12

## Dataframe Attributes and Methods

In [7]:
# shape
print(f"Movies shape:{movies.shape}") # show rows and column
print(f"PSL Matches shape:{psl_matches.shape}")

Movies shape:(153, 10)
PSL Matches shape:(173, 12)

In [110]:
# dtype
print(f"Movies Dtypes:\n{"-"*30}\n{movies.dtypes}")
print("~"*30)
print(f"PSL Matches Dtypes:\n{"-"*30}\n{psl_matches.dtypes}")

Movies Dtypes:
------------------------------
MovieID                      str
Title                        str
Genre                        str
ReleaseYear                int64
Director                     str
Language                     str
Duration_min               int64
IMDB_Rating              float64
Votes                      int64
BoxOffice_Million_USD    float64
dtype: object
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSL Matches Dtypes:
------------------------------
MatchID               str
Season              int64
Date                  str
Team1                 str
Team2                 str
Venue                 str
TossWinner            str
TossDecision          str
Team1_Score           str
Team2_Score           str
Winner                str
PlayerOfTheMatch      str
dtype: object

In [111]:
# index
movies.index

RangeIndex(start=0, stop=153, step=1)

In [112]:
psl_matches.index

RangeIndex(start=0, stop=173, step=1)

In [ ]:
#columns
movies.columns

Index(['MovieID', 'Title', 'Genre', 'ReleaseYear', 'Director', 'Language',
       'Duration_min', 'IMDB_Rating', 'Votes', 'BoxOffice_Million_USD'],
      dtype='str')

In [114]:
psl_matches.columns

Index(['MatchID', 'Season', 'Date', 'Team1', 'Team2', 'Venue', 'TossWinner',
       'TossDecision', 'Team1_Score', 'Team2_Score', 'Winner',
       'PlayerOfTheMatch'],
      dtype='str')

In [118]:
# values
student_record.values

array([['Mathematics', 85, 100, 'A'],
       ['Computer Science', 92, 100, 'A+'],
       ['Physics', 78, 100, 'B'],
       ['Chemistry', 83, 100, 'B+'],
       ['English', 88, 100, 'A'],
       ['Data Science', 95, 100, 'A+'],
       ['Machine Learning', 90, 100, 'A+'],
       ['Operating Systems', 81, 100, 'B+'],
       ['Digital Logic Design', 87, 100, 'A'],
       ['Technical Writing', 84, 100, 'B+']], dtype=object)

In [123]:
df1.values

array([[100,  96,  10],
       [ 90,  80,   8],
       [ 76,  56,   7],
       [ 66,  60,   5]])

In [124]:
movies.values

array([['M0072', 'The Eternal Signal', 'Sci-Fi', ..., 5.7, 15685, 26.1],
       ['M0005', 'The Secret Legacy', 'Sci-Fi', ..., 4.6, 75504, 16.0],
       ['M0100', 'The Shattered Storm', 'Sci-Fi', ..., 8.1, 14538, 43.8],
       ...,
       ['M0110', 'The Eternal River', 'Sci-Fi', ..., 7.4, 68089, 33.7],
       ['M0107', 'The Eternal Shadow', 'Romance', ..., 8.9, 11474, 1.2],
       ['M0139', 'The Frozen Warrior', 'Documentary', ..., 7.6, 27238,
        nan]], shape=(153, 10), dtype=object)

In [125]:
psl_matches.values

array([['PSL0026', 2021, '07/03/2021', ..., '130/10', 'Karachi Kings',
        'Player 39'],
       ['PSL0053', 2022, '2022-02-28', ..., '138/6', 'Peshawar Zalmi',
        'Player 8'],
       ['PSL0150', 2025, '23-Feb-2025', ..., '135/5', 'Multan Sultans',
        'Player 29'],
       ...,
       ['PSL0134', 2024, '12-Mar-2024', ..., '195/6', 'Karachi Kings',
        'Player 9'],
       ['PSL0106', 2024, '13-Feb-2024', ..., '169/3', 'Islamabad United',
        'Player 3'],
       ['PSL0085', 2023, '2023-02-26', ..., '160/3', 'Lahore Qalandars',
        'Player 12']], shape=(173, 12), dtype=object)

In [75]:
# head and tails
psl_matches.head()

,Season,Date,Team1,Team2,Venue,TossWinner,TossDecision,Team1_Score,Team2_Score,Winner,PlayerOfTheMatch
MatchID,,,,,,,,,,,
PSL0026,2021,07/03/2021,Karachi Kings,Lahore Qalandars,Rawalpindi Cricket Stadium,Lahore Qalandars,Field,120/2,130/10,Karachi Kings,Player 39
PSL0053,2022,2022-02-28,Peshawar Zalmi,multan sultans,"Gaddafi Stadium, Lahore",Multan Sultans,Field,150/4,138/6,Peshawar Zalmi,Player 8
PSL0150,2025,23-Feb-2025,Lahore Qalandars,Multan Sultans,Pindi Cricket Stadium,Lahore Qalandars,Bat,161/6,135/5,Multan Sultans,Player 29
PSL0089,2023,02/03/2023,Karachi Kings,Quetta Gladiators,Rawalpindi Cricket Stadium,Karachi Kings,Bat,141/4,183/7,Quetta Gladiators,Player 40
PSL0114,2024,2024-02-21,Karachi Kings,Islamabad United,"National Stadium, Karachi",Karachi Kings,Bat,125/5,151/2,Karachi Kings,Player 5

In [76]:
movies.head()

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0072,The Eternal Signal,Sci-Fi,2009,Anna Johnson,Urdu,180,5.7,15685,26.1
M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0
M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8
M0103,The Shattered Empire,Animation,2014,Mina Ahmed,Hindi,101,5.8,2579,8.3
M0003,The Frozen Path,Action,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0

In [128]:
psl_matches.tail(3)

,MatchID,Season,Date,Team1,Team2,Venue,TossWinner,TossDecision,Team1_Score,Team2_Score,Winner,PlayerOfTheMatch
170,PSL0134,2024,12-Mar-2024,Lahore Qalandars,Karachi Kings,"Gaddafi Stadium, Lahore",Karachi Kings,Bat,215/7,195/6,Karachi Kings,Player 9
171,PSL0106,2024,13-Feb-2024,Islamabad United,Multan Sultans,"National Stadium, Karachi",Islamabad United,Field,129/3,169/3,Islamabad United,Player 3
172,PSL0085,2023,2023-02-26,Lahore Qalandars,Peshawar Zalmi,Rawalpindi Cricket Stadium,Lahore Qalandars,Bat,167/6,160/3,Lahore Qalandars,Player 12

In [129]:
movies.tail()

,MovieID,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
148,M0048,The Silent Echo,Comedy,2018,James Chen,Punjabi,96,3.4,32466,8.8
149,M0080,The Broken Flame,Action,2007,Ayesha Smith,Hindi,128,7.1,2559,12.1
150,M0110,The Eternal River,Sci-Fi,2014,Hassan Ahmed,Punjabi,116,7.4,68089,33.7
151,M0107,The Eternal Shadow,Romance,2019,Nadia Garcia,Hindi,133,8.9,11474,1.2
152,M0139,The Frozen Warrior,Documentary,2019,Omar Ahmed,Punjabi,127,7.6,27238,NaN

In [ ]:
# sample
movies.sample() # it wil us a random values

,MovieID,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
124,M0086,The Endless City,Drama,2014,James Smith,Urdu,144,NaN,12414,56.6

In [ ]:
movies.sample(5) # that will give us the randomly sample values

,MovieID,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
48,M0055,The Burning Shadow,Thriller,2014,Robert Chen,Urdu,137,5.2,56089,6.3
21,M0099,The Forgotten Garden,Thriller,2023,Ayesha Chen,Hindi,140,5.8,3293,6.6
44,M0093,The Rising Warrior,Animation,2007,Carlos Ahmed,Korean,125,5.0,220191,NaN
108,M0125,The Lost Kingdom,Animation,2011,Omar Garcia,English,129,6.8,137869,47.5
81,M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8

In [133]:
# info
print(movies.info())

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MovieID                153 non-null    str
 1   Title                  153 non-null    str
 2   Genre                  153 non-null    str
 3   ReleaseYear            153 non-null    int64
 4   Director               153 non-null    str
 5   Language               153 non-null    str
 6   Duration_min           153 non-null    int64
 7   IMDB_Rating            144 non-null    float64
 8   Votes                  153 non-null    int64
 9   BoxOffice_Million_USD  143 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 12.1 KB
None

In [135]:
print(movies.describe())

       ReleaseYear  Duration_min  IMDB_Rating          Votes  \
count   153.000000    153.000000   144.000000     153.000000
mean   2012.960784    113.967320     6.688194   43222.745098
std       7.663895     18.952995     1.165560   44823.345144
min    1998.000000     75.000000     3.400000     183.000000
25%    2006.000000    101.000000     5.800000   11082.000000
50%    2014.000000    115.000000     6.800000   28227.000000
75%    2019.000000    126.000000     7.400000   63423.000000
max    2026.000000    180.000000     9.600000  220191.000000

       BoxOffice_Million_USD
count             143.000000
mean               30.337063
std                27.674719
min                 0.500000
25%                 9.200000
50%                23.000000
75%                43.400000
max               129.400000

In [139]:
# isnull
movies.isnull().sum()

MovieID                   0
Title                     0
Genre                     0
ReleaseYear               0
Director                  0
Language                  0
Duration_min              0
IMDB_Rating               9
Votes                     0
BoxOffice_Million_USD    10
dtype: int64

In [ ]:
# returns the sum of the null values
psl_matches.isnull().sum()

MatchID              0
Season               0
Date                 0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
Team1_Score          7
Team2_Score          3
Winner              16
PlayerOfTheMatch    16
dtype: int64

In [10]:
movies.duplicated()# this will give in the form of boolean

0      False
1      False
2      False
3      False
4      False
       ...
148     True
149    False
150    False
151    False
152    False
Length: 153, dtype: bool

In [12]:
print(movies.duplicated().sum())

3

In [18]:
print(psl_matches.duplicated().sum())

3

In [28]:
# rename
student_record.columns

Index(['Subject', 'Marks_Obtained', 'Total_Marks', 'Grade'], dtype='str')

In [35]:
student_record.rename(columns={'Marks_Obtained':'Obtained Marks'},inplace=True)

In [ ]:
student_record # see the changes are made permanent due to inplace

                Subject  Obtained Marks  Total_Marks Grade
0           Mathematics              85          100     A
1      Computer Science              92          100    A+
2               Physics              78          100     B
3             Chemistry              83          100    B+
4               English              88          100     A
5          Data Science              95          100    A+
6      Machine Learning              90          100    A+
7     Operating Systems              81          100    B+
8  Digital Logic Design              87          100     A
9     Technical Writing              84          100    B+

## Math Methods

In [47]:
# sum()
student_record[['Obtained Marks','Total_Marks']].sum()

Obtained Marks     863
Total_Marks       1000
dtype: int64

In [48]:
# by rowwise and column wise
student_record[['Obtained Marks', 'Total_Marks']].sum(axis=1) # row wise

0    185
1    192
2    178
3    183
4    188
5    195
6    190
7    181
8    187
9    184
dtype: int64

In [50]:
student_record[['Obtained Marks', 'Total_Marks']].sum(axis=0) # column wise sum

Obtained Marks     863
Total_Marks       1000
dtype: int64

In [51]:
# mean
student_record[['Obtained Marks', 'Total_Marks']].mean(axis=1)

0    92.5
1    96.0
2    89.0
3    91.5
4    94.0
5    97.5
6    95.0
7    90.5
8    93.5
9    92.0
dtype: float64

In [52]:
student_record[['Obtained Marks', 'Total_Marks']].mean(axis=0)

Obtained Marks     86.3
Total_Marks       100.0
dtype: float64

In [53]:
# mode
student_record[['Obtained Marks', 'Total_Marks']].mode(axis=1)

    0    1
0  85  100
1  92  100
2  78  100
3  83  100
4  88  100
5  95  100
6  90  100
7  81  100
8  87  100
9  84  100

In [ ]:
student_record[['Obtained Marks', 'Total_Marks']].mode(axis=0) # column wise

   Obtained Marks  Total_Marks
0              78        100.0
1              81          NaN
2              83          NaN
3              84          NaN
4              85          NaN
5              87          NaN
6              88          NaN
7              90          NaN
8              92          NaN
9              95          NaN

In [55]:
# varience
student_record[['Obtained Marks', 'Total_Marks']].var(axis=1)

0    112.5
1     32.0
2    242.0
3    144.5
4     72.0
5     12.5
6     50.0
7    180.5
8     84.5
9    128.0
dtype: float64

In [56]:
student_record[['Obtained Marks', 'Total_Marks']].var(axis=0)

Obtained Marks    26.677778
Total_Marks        0.000000
dtype: float64

In [ ]:
# std
student_record[['Obtained Marks', 'Total_Marks']].std(axis=1)

0    10.606602
1     5.656854
2    15.556349
3    12.020815
4     8.485281
5     3.535534
6     7.071068
7    13.435029
8     9.192388
9    11.313708
dtype: float64

In [ ]:
# std
student_record[['Obtained Marks', 'Total_Marks']].std(axis=0)

Obtained Marks    5.165054
Total_Marks       0.000000
dtype: float64

In [59]:
# product
student_record[['Obtained Marks', 'Total_Marks']].product(axis=1)

0    8500
1    9200
2    7800
3    8300
4    8800
5    9500
6    9000
7    8100
8    8700
9    8400
dtype: int64

In [60]:
student_record[['Obtained Marks', 'Total_Marks']].product(axis=0)

Obtained Marks    4101451474504784384
Total_Marks       7766279631452241920
dtype: int64

## Selecting Columnns from a dataframe

In [61]:
# single column
movies.columns

Index(['MovieID', 'Title', 'Genre', 'ReleaseYear', 'Director', 'Language',
       'Duration_min', 'IMDB_Rating', 'Votes', 'BoxOffice_Million_USD'],
      dtype='str')

In [63]:
# try to fetch out the single column
movies['Title'].head(10)

0      The Eternal Signal
1       The Secret Legacy
2     The Shattered Storm
3    The Shattered Empire
4         The Frozen Path
5      The Frozen Kingdom
6    The Midnight Journey
7        The Frozen Dream
8        The Hidden Dream
9         The Rising City
Name: Title, dtype: str

In [64]:
# multiple columns
movies[['Title','Votes','Language']]

                    Title  Votes Language
0      The Eternal Signal  15685     Urdu
1       The Secret Legacy  75504   Korean
2     The Shattered Storm  14538  English
3    The Shattered Empire   2579    Hindi
4         The Frozen Path  21717   Korean
..                    ...    ...      ...
148       The Silent Echo  32466  Punjabi
149      The Broken Flame   2559    Hindi
150     The Eternal River  68089  Punjabi
151    The Eternal Shadow  11474    Hindi
152    The Frozen Warrior  27238  Punjabi

[153 rows x 3 columns]

In [65]:
psl_matches.columns

Index(['MatchID', 'Season', 'Date', 'Team1', 'Team2', 'Venue', 'TossWinner',
       'TossDecision', 'Team1_Score', 'Team2_Score', 'Winner',
       'PlayerOfTheMatch'],
      dtype='str')

In [67]:
psl_matches[['Team1','Team2','Team1_Score','Team2_Score','Winner']].head(10)

,Team1,Team2,Team1_Score,Team2_Score,Winner
0,Karachi Kings,Lahore Qalandars,120/2,130/10,Karachi Kings
1,Peshawar Zalmi,multan sultans,150/4,138/6,Peshawar Zalmi
2,Lahore Qalandars,Multan Sultans,161/6,135/5,Multan Sultans
3,Karachi Kings,Quetta Gladiators,141/4,183/7,Quetta Gladiators
4,Karachi Kings,Islamabad United,125/5,151/2,Karachi Kings
5,Islamabad United,Multan Sultans,193/3,180/10,Multan Sultans
6,QUETTA GLADIATORS,Karachi Kings,182/6,202/3,NaN
7,Islamabad United,Karachi Kings,148/5,163/3,Karachi Kings
8,Multan Sultans,Karachi Kings,156/6,173/6,Multan Sultans
9,Islamabad United,Multan Sultans,185/8,148/4,NaN

## Selecting the Rows

In [ ]:
movies.iloc[2:4] # 2 and three index number

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8
M0103,The Shattered Empire,Animation,2014,Mina Ahmed,Hindi,101,5.8,2579,8.3

In [ ]:
movies.iloc[2:16:2] # gives the alternative

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0100,The Shattered Storm,Sci-Fi,2024,Anna Johnson,English,91,8.1,14538,43.8
M0003,The Frozen Path,Action,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0
M0130,The Midnight Journey,Sci-Fi,2011,Wei Garcia,Punjabi,136,NaN,58867,5.7
M0065,The Hidden Dream,Documentary,2014,Omar Khan,URDU,130,7.6,92583,43.0
M0060,The Hidden Echo,Sci-Fi,2000,Mina Lee,Urdu,115,6.4,22744,18.3
M0056,The Burning Flame,Thriller,2023,Nadia Lee,Urdu,90,6.7,173280,17.7
M0119,The Silent Horizon,Documentary,2024,Michael Malik,Hindi,120,7.2,8787,9.9

In [84]:
# fancy indexing
movies.iloc[[1,7,20,27]]

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0
M0089,The Frozen Dream,Thriller,2014,James Johnson,Spanish,116,5.3,10318,5.5
M0040,The Eternal Echo,Romance,2023,Robert Ahmed,Urdu,111,6.9,80406,9.2
M0075,The Lost City,thriller,2006,Anna Chen,HINDI,119,6.9,4069,23.4

In [88]:
# loc find with the index label
student_record.loc['Mathematics']

Marks_Obtained     85
Total_Marks       100
Grade               A
Name: Mathematics, dtype: object

In [98]:
movies.loc["M0003":"M0089"]

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD
MovieID,,,,,,,,,
M0003,The Frozen Path,Action,2010,Ayesha Rodriguez,Korean,114,7.2,21717,61.0
M0046,The Frozen Kingdom,Sci-Fi,2015,Omar Johnson,spanish,118,5.6,47780,23.5
M0130,The Midnight Journey,Sci-Fi,2011,Wei Garcia,Punjabi,136,NaN,58867,5.7
M0089,The Frozen Dream,Thriller,2014,James Johnson,Spanish,116,5.3,10318,5.5

In [101]:
a=movies.loc["M0003":"M0089":2] # will give the alternative

In [96]:
# fancy indexing on the loc
student_record.loc[["Physics","Machine Learning","Technical Writing"]]

                   Marks_Obtained  Total_Marks Grade
Subject
Physics                        78          100     B
Machine Learning               90          100    A+
Technical Writing              84          100    B+

## Selecting Both Rows And Columns

In [ ]:
student_record.iloc[0:3,0:3] # first 3 rows and first three columns

                  Marks_Obtained  Total_Marks Grade
Subject
Mathematics                   85          100     A
Computer Science              92          100    A+
Physics                       78          100     B

In [ ]:
movies.iloc[4:15,3:6] #rows will be from 4 to 14 and columns from 3,4, and 5

                 Director Language  Duration_min
MovieID
M0003    Ayesha Rodriguez   Korean           114
M0046        Omar Johnson  spanish           118
M0130          Wei Garcia  Punjabi           136
M0089       James Johnson  Spanish           116
M0065           Omar Khan     URDU           130
M0105         Sofia Ahmed     Urdu            89
M0060            Mina Lee     Urdu           115
M0073        Omar Johnson  English           126
M0056           Nadia Lee     Urdu            90
M0138        Hassan Smith  English           112
M0119       Michael Malik    Hindi           120

In [106]:
movies.iloc[0:4,[0,4,8]]

                        Title Language  BoxOffice_Million_USD
MovieID
M0072      The Eternal Signal     Urdu                   26.1
M0005       The Secret Legacy   Korean                   16.0
M0100     The Shattered Storm  English                   43.8
M0103    The Shattered Empire    Hindi                    8.3

## Filtering a Dataset

In [121]:
# fetch all the data in which the winner is Karachi King
winner=psl_matches[psl_matches["Winner"]=="Karachi Kings"]
winner
# second condition is that get the season
winner[['Season','Winner']]

         Season         Winner
MatchID
PSL0026    2021  Karachi Kings
PSL0114    2024  Karachi Kings
PSL0024    2021  Karachi Kings
PSL0133    2024  Karachi Kings
PSL0057    2022  Karachi Kings
PSL0129    2024  Karachi Kings
PSL0148    2025  Karachi Kings
PSL0170    2025  Karachi Kings
PSL0152    2025  Karachi Kings
PSL0073    2023  Karachi Kings
PSL0012    2021  Karachi Kings
PSL0079    2023  Karachi Kings
PSL0159    2025  Karachi Kings
PSL0003    2021  Karachi Kings
PSL0022    2021  Karachi Kings
PSL0061    2022  Karachi Kings
PSL0072    2023  Karachi Kings
PSL0054    2022  Karachi Kings
PSL0099    2023  Karachi Kings
PSL0061    2022  Karachi Kings
PSL0049    2022  Karachi Kings
PSL0134    2024  Karachi Kings

In [124]:
# now get the team one an dteam 2 names
winner[["Season","Team1","Team2","Winner"]]

         Season              Team1              Team2         Winner
MatchID
PSL0026    2021      Karachi Kings   Lahore Qalandars  Karachi Kings
PSL0114    2024      Karachi Kings   Islamabad United  Karachi Kings
PSL0024    2021   Islamabad United      Karachi Kings  Karachi Kings
PSL0133    2024      Karachi Kings   Lahore Qalandars  Karachi Kings
PSL0057    2022      Karachi Kings     Multan Sultans  Karachi Kings
PSL0129    2024      Karachi Kings   Lahore Qalandars  Karachi Kings
PSL0148    2025      KARACHI KINGS  Quetta Gladiators  Karachi Kings
PSL0170    2025      Karachi Kings   Lahore Qalandars  Karachi Kings
PSL0152    2025     Peshawar Zalmi      Karachi Kings  Karachi Kings
PSL0073    2023      Karachi Kings   Islamabad United  Karachi Kings
PSL0012    2021      Karachi Kings     Peshawar Zalmi  Karachi Kings
PSL0079    2023   Islamabad United      Karachi Kings  Karachi Kings
PSL0159    2025      Karachi Kings   Islamabad United  Karachi Kings
PSL0003    2021  Quetta Gladiators      Karachi Kings  Karachi Kings
PSL0022    2021   Islamabad United      Karachi Kings  Karachi Kings
PSL0061    2022     Multan Sultans      Karachi Kings  Karachi Kings
PSL0072    2023   LAHORE QALANDARS      Karachi Kings  Karachi Kings
PSL0054    2022     Peshawar Zalmi      Karachi Kings  Karachi Kings
PSL0099    2023      Karachi Kings     Peshawar Zalmi  Karachi Kings
PSL0061    2022     Multan Sultans      Karachi Kings  Karachi Kings
PSL0049    2022      Karachi Kings   Islamabad United  Karachi Kings
PSL0134    2024   Lahore Qalandars      Karachi Kings  Karachi Kings

In [126]:
# now wants to see the both teams score
winner[["Team1","Team2","Team1_Score","Team2_Score","Winner"]]

,Team1,Team2,Team1_Score,Team2_Score,Winner
MatchID,,,,,
PSL0026,Karachi Kings,Lahore Qalandars,120/2,130/10,Karachi Kings
PSL0114,Karachi Kings,Islamabad United,125/5,151/2,Karachi Kings
PSL0024,Islamabad United,Karachi Kings,148/5,163/3,Karachi Kings
PSL0133,Karachi Kings,Lahore Qalandars,209/8,162/3,Karachi Kings
PSL0057,Karachi Kings,Multan Sultans,141/2,NaN,Karachi Kings
PSL0129,Karachi Kings,Lahore Qalandars,178/4,143/2,Karachi Kings
PSL0148,KARACHI KINGS,Quetta Gladiators,154/8,184/5,Karachi Kings
PSL0170,Karachi Kings,Lahore Qalandars,125/4,141/6,Karachi Kings
PSL0152,Peshawar Zalmi,Karachi Kings,170/4,116/5,Karachi Kings
PSL0073,Karachi Kings,Islamabad United,138/5,180/7,Karachi Kings
PSL0012,Karachi Kings,Peshawar Zalmi,194/10,155/10,Karachi Kings
PSL0079,Islamabad United,Karachi Kings,188/10,145/7,Karachi Kings
PSL0159,Karachi Kings,Islamabad United,190/8,198/5,Karachi Kings
PSL0003,Quetta Gladiators,Karachi Kings,172/6,130/9,Karachi Kings
PSL0022,Islamabad United,Karachi Kings,136/9,172/6,Karachi Kings
PSL0061,Multan Sultans,Karachi Kings,NaN,170/2,Karachi Kings
PSL0072,LAHORE QALANDARS,Karachi Kings,122/10,175/2,Karachi Kings
PSL0054,Peshawar Zalmi,Karachi Kings,152/8,186/6,Karachi Kings
PSL0099,Karachi Kings,Peshawar Zalmi,144/3,112/9,Karachi Kings
PSL0061,Multan Sultans,Karachi Kings,NaN,170/2,Karachi Kings
PSL0049,Karachi Kings,Islamabad United,154/6,177/9,Karachi Kings
PSL0134,Lahore Qalandars,Karachi Kings,215/7,195/6,Karachi Kings

In [127]:
# just want to see the season and winner
winner[["Season","Winner"]]

         Season         Winner
MatchID
PSL0026    2021  Karachi Kings
PSL0114    2024  Karachi Kings
PSL0024    2021  Karachi Kings
PSL0133    2024  Karachi Kings
PSL0057    2022  Karachi Kings
PSL0129    2024  Karachi Kings
PSL0148    2025  Karachi Kings
PSL0170    2025  Karachi Kings
PSL0152    2025  Karachi Kings
PSL0073    2023  Karachi Kings
PSL0012    2021  Karachi Kings
PSL0079    2023  Karachi Kings
PSL0159    2025  Karachi Kings
PSL0003    2021  Karachi Kings
PSL0022    2021  Karachi Kings
PSL0061    2022  Karachi Kings
PSL0072    2023  Karachi Kings
PSL0054    2022  Karachi Kings
PSL0099    2023  Karachi Kings
PSL0061    2022  Karachi Kings
PSL0049    2022  Karachi Kings
PSL0134    2024  Karachi Kings

## Adding New Columns

In [129]:
# let say try to add new one columns at the last
movies["Country"]="Uk"

In [130]:
movies.head(2)

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD,Country
MovieID,,,,,,,,,,
M0072,The Eternal Signal,Sci-Fi,2009,Anna Johnson,Urdu,180,5.7,15685,26.1,Uk
M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0,Uk

In [135]:
# from existing one
movies.dropna(inplace=True)

In [140]:
movies["Lead Actre"]=movies["Director"].str.split("|").apply(lambda x: x[0])

In [142]:
movies.head(2)

,Title,Genre,ReleaseYear,Director,Language,Duration_min,IMDB_Rating,Votes,BoxOffice_Million_USD,Country,Lead Actre
MovieID,,,,,,,,,,,
M0072,The Eternal Signal,Sci-Fi,2009,Anna Johnson,Urdu,180,5.7,15685,26.1,Uk,Anna Johnson
M0005,The Secret Legacy,Sci-Fi,2024,Emma Farooq,Korean,148,4.6,75504,16.0,Uk,Emma Farooq

# Method

In [147]:
# astype
psl_matches["Season"]=psl_matches["Season"].astype("int32")

In [ ]:
psl_matches.info() # see the Season column is now 32 integer

<class 'pandas.DataFrame'>
Index: 173 entries, PSL0026 to PSL0085
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            173 non-null    int32
 1   Date              173 non-null    str
 2   Team1             173 non-null    str
 3   Team2             173 non-null    str
 4   Venue             173 non-null    str
 5   TossWinner        173 non-null    str
 6   TossDecision      173 non-null    str
 7   Team1_Score       166 non-null    str
 8   Team2_Score       170 non-null    str
 9   Winner            157 non-null    str
 10  PlayerOfTheMatch  157 non-null    str
dtypes: int32(1), str(10)
memory usage: 19.6+ KB

In [150]:
psl_matches.value_counts().head(2)

Season  Date        Team1             Team2             Venue                    TossWinner        TossDecision  Team1_Score  Team2_Score  Winner            PlayerOfTheMatch
2024    2024-02-28  Lahore Qalandars  Islamabad United  Gaddafi Stadium, Lahore  Lahore Qalandars  Field         203/5        196/9        Islamabad United  Player 29           2
2021    2021-02-20  Karachi Kings     multan sultans    Pindi Cricket Stadium    Multan Sultans    Field         194/9        176/5        Multan Sultans    Player 16           2
Name: count, dtype: int64